# DONT READ THE DICTINARY
# YOU DONT NEED TO KNOW EVERYTHING ABOUT A PROGRAMMING LANGUAGE.
# LEARN HOW TO LEARN AND HOW TO FIND OUT WHAT YOU NEED TO KNOW, USE IT, AND THEN MOVE ON UNTIL YOU NEED TO FIND OUT THE NEXT THING YOU NEED TO KNOW